name: Fetch Clash of Clans Raid Weekend Data

on:
  schedule:
    # Friday 07:00–23:00 UTC
    - cron: "0 7-23 * * 5"

    # Saturday every hour
    - cron: "0 * * * 6"

    # Sunday every hour
    - cron: "0 * * * 0"

    # Monday 00:00–06:00 UTC
    - cron: "0 0-6 * * 1"

    # Monday 06:50 UTC
    - cron: "50 6 * * 1"

  workflow_dispatch:  # Allows manual trigger

concurrency:
  group: repo-write-lock
  cancel-in-progress: false

jobs:
  fetch-war-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch War Data
        env:
          COC_API_KEY: ${{ secrets.COC_API_KEY }}
        run: |
          python GatherRaidWeekendData.py


      - name: Commit and Push War Data
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CoC 
          author_email: coc@coc.nl
          message: ''
