name: Fetch Clash of Clans Clan and Member Data

on:
  schedule:
    - cron: "0 8-23 * * *"   # Every hour from 08:00 to 23:00
    - cron: "0 0 * * *"      # Also run at 00:00
  workflow_dispatch: # Allows manual trigger

concurrency:
  group: repo-write-lock
  cancel-in-progress: false

jobs:
  fetch-war-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch War Data
        env:
          COC_API_KEY: ${{ secrets.COC_API_KEY }}
        run: |
          python GatherClanData.py


      - name: Commit and Push War Data
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CoC 
          author_email: coc@coc.nl
          message: ''
